[workspace]
authors = ["deepthought <deepthough@postech.ac.kr>"]
channels = ["conda-forge"]
name = "pymol_lowpoly"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11"
pymol-open-source = ">=3.1.0,<4"
numpy = ">=2.3.5,<3"
scipy = ">=1.16.3,<2"
pytest = ">=9.0.2,<10"
